### ISSUE TITLE
     Cannot find module 'rc-util/lib/isMobile' from 'StepHandler.js'

### ISSUE THREAD

**Issue by anotheri** [react-component/util#208]
after update to `antd` to 4.13.0, it looks like `rc-util` has been updated from "^5.7.0" to "^5.8.1" and now i'm getting this error
```
Cannot find module 'rc-util/lib/isMobile' from 'StepHandler.js'
      at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (node_modules/rc-input-number/lib/StepHandler.js:20:40)
```
please advice.

**Comment by anotheri** [comment]
downgrade to `5.8.0` fixed the problem

**Comment by anotheri** [comment]
It seems to be fixed with the latest `antd`, so I've been able to remove the `5.8.0` dependency from the `package.json`.
Closing the issue.
